// main components
export { default as About } from './About'
export { default as Community } from './Community'
export { default as FAQs } from './FAQs'
export { default as Footer } from './Footer'
export { default as Hero } from './Hero'
export { default as HowItWorks } from './HowItWorks'
export { default as JoinUs } from './JoinUs'
export { default as Navbar } from './Navbar'
export { default as Objective } from './Objective'
export { default as Services } from './Services'
export { default as Team } from './Team'
export { default as Blog } from './Blog'
export { default as Contact } from './Contact'
export { default as Location } from './Location'
export { default as CTA } from './CTA'